service: aml-workshop-lambda-fastapi

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${env:STAGE}

functions:
  app:
    handler: main.handler

plugins:
  - serverless-python-requirements
